# Generated by Django 5.0.7 on 2024-08-12 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.user')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.user')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='产品介绍')),
            ],
        ),
    ]
