# Generated by Django 5.0.7 on 2024-08-13 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_customer_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='designer',
            fields=[
                ('designer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.user')),
                ('personal_description', models.TextField(verbose_name='个人介绍')),
                ('portfolio_link', models.URLField(verbose_name='作品集链接')),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='user_id',
            new_name='supplier',
        ),
        migrations.CreateModel(
            name='cus_sup_communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='cus_sup_follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.supplier')),
            ],
        ),
    ]
