# Generated by Django 5.0.7 on 2024-08-13 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_order_logistics_information_product_order_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_to_cart',
            new_name='add_product_to_cart',
        ),
        migrations.RenameModel(
            old_name='add_to_favorite',
            new_name='add_product_to_favorite',
        ),
        migrations.RenameModel(
            old_name='review',
            new_name='product_review',
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.designer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.product')),
            ],
        ),
        migrations.CreateModel(
            name='cus_des_communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.designer')),
            ],
        ),
        migrations.CreateModel(
            name='cus_des_follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.designer')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.designer')),
            ],
        ),
        migrations.CreateModel(
            name='add_project_to_favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.project')),
            ],
        ),
        migrations.CreateModel(
            name='project_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.project')),
            ],
        ),
    ]
