# Generated by Django 5.0.7 on 2024-08-13 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_rename_add_to_cart_add_product_to_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='product',
        ),
        migrations.AddField(
            model_name='contract',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='system.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customer')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.designer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.project')),
            ],
        ),
    ]
