# Generated by Django 4.2.14 on 2024-09-08 23:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caseid", models.IntegerField()),
                ("userid", models.IntegerField()),
                ("size", models.IntegerField(default=0, verbose_name="点赞数")),
                ("content", models.CharField(max_length=500, verbose_name="评论内容")),
                ("type", models.CharField(max_length=20, verbose_name="样例类型")),
            ],
        ),
        migrations.CreateModel(
            name="comment_like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_id", models.IntegerField()),
                ("user_id", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="custome_case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="建筑名称")),
                ("longitude", models.FloatField(verbose_name="经度")),
                ("latitude", models.FloatField(verbose_name="纬度")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="地址"
                    ),
                ),
                ("size", models.IntegerField(verbose_name="点赞数")),
                ("type", models.CharField(max_length=20, verbose_name="案例类型")),
                (
                    "designer",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="设计者"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=800, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "mid_time",
                    models.DateField(blank=True, null=True, verbose_name="中期时间"),
                ),
                (
                    "mid_cover",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="中期封面"
                    ),
                ),
                (
                    "term_time",
                    models.DateField(blank=True, null=True, verbose_name="终期时间"),
                ),
                (
                    "term_cover",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="终期封面"
                    ),
                ),
                (
                    "video",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="视频"
                    ),
                ),
                (
                    "tag",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "mid_album",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "term_album",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="earthquakes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=200, verbose_name="发生时间")),
                (
                    "magnitude",
                    models.CharField(max_length=10, null=True, verbose_name="震级"),
                ),
                (
                    "location",
                    models.CharField(max_length=200, null=True, verbose_name="位置"),
                ),
                ("longitude", models.FloatField(verbose_name="经度")),
                ("latitude", models.FloatField(verbose_name="纬度")),
                ("depth_km", models.FloatField(verbose_name="深度（公里）")),
                ("date", models.DateField(verbose_name="日期")),
            ],
        ),
        migrations.CreateModel(
            name="excellent_case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="建筑名称")),
                ("longitude", models.FloatField(verbose_name="经度")),
                ("latitude", models.FloatField(verbose_name="纬度")),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="url"
                    ),
                ),
                ("size", models.IntegerField(verbose_name="点赞数")),
                (
                    "designer",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="设计者"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="供应商"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="地址"
                    ),
                ),
                ("area", models.IntegerField(blank=True, null=True, verbose_name="面积")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "img",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caseid", models.IntegerField()),
                ("userid", models.IntegerField()),
                ("type", models.CharField(max_length=20, verbose_name="样例类型")),
            ],
        ),
    ]
